services:
  - type: web
    name: 2morefitness
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn gym_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: STATIC_ADMIN_USERNAME
        value: gymadmin
      - key: STATIC_ADMIN_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: 2morefitness-db
          property: connectionString

  - type: pserver
    name: 2morefitness-db
    runtime: postgresql
    plan: free
    databaseName: gymdb
    databaseUser: gymuser
